# Generated by Django 5.0 on 2023-12-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookins',
            name='client_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookins',
            name='Address',
            field=models.CharField(default='nil', max_length=120),
        ),
        migrations.AlterField(
            model_name='bookins',
            name='Book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Uaaagghh.services'),
        ),
        migrations.AlterField(
            model_name='bookins',
            name='Client_Name',
            field=models.CharField(default='NIL', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookins',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
