# Generated by Django 5.0 on 2023-12-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0002_bookins_client_number_alter_bookins_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='services_cateogaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogary', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bookins',
            name='cateogary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Uaaagghh.services_cateogaries'),
        ),
    ]
