# Generated by Django 5.0 on 2023-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0003_services_cateogaries_bookins_cateogary'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_cateogaries',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='services_cateogaries',
            name='cateogary',
            field=models.CharField(default='NIL', max_length=200),
        ),
    ]
