# Generated by Django 5.0 on 2023-12-22 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0004_services_cateogaries_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Uaaagghh.services_cateogaries'),
        ),
    ]
