# Generated by Django 5.0 on 2023-12-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0005_services_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Ph', models.CharField(max_length=10)),
                ('Email', models.CharField(default='Not Assigned By User', max_length=200)),
            ],
        ),
    ]
