# Generated by Django 5.0 on 2023-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
