# Generated by Django 5.0 on 2024-01-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0010_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='Services'),
        ),
    ]
