# Generated by Django 5.0 on 2024-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0011_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookins',
            name='Address',
            field=models.CharField(default='nil', max_length=1000),
        ),
    ]
