# Generated by Django 5.0 on 2024-01-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0012_alter_bookins_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
