# Generated by Django 5.0 on 2024-01-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0013_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_cateogaries',
            name='image',
            field=models.ImageField(blank=True, upload_to='categaries'),
        ),
    ]
