# Generated by Django 5.0 on 2024-01-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0014_alter_services_cateogaries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookins',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
