# Generated by Django 5.0 on 2024-01-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uaaagghh', '0016_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='gall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Gallery')),
            ],
        ),
    ]
